version: '3'

services:
  app:
    build: .
    image: my_app_image
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - REDIS_ADDR=redis:6379

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
